#ifndef TOON_RP_LIGHTING_DEFINES
#define TOON_RP_LIGHTING_DEFINES

#if defined(_TOON_RP_ADDITIONAL_LIGHTS) || defined(_TOON_RP_ADDITIONAL_LIGHTS_VERTEX) || defined(_TOON_RP_TILED_LIGHTING)
#define TOON_RP_ADDITIONAL_LIGHTS_ANY
#endif // _TOON_RP_ADDITIONAL_LIGHTS || _TOON_RP_ADDITIONAL_LIGHTS_VERTEX || _TOON_RP_TILED_LIGHTING

#if defined(_TOON_RP_ADDITIONAL_LIGHTS) || defined(_TOON_RP_TILED_LIGHTING)
#define TOON_RP_ADDITIONAL_LIGHTS_ANY_PER_PIXEL
#endif // _TOON_RP_ADDITIONAL_LIGHTS || _TOON_RP_TILED_LIGHTING

#endif // TOON_RP_LIGHTING_DEFINES