#ifndef TOON_SHADER_PASS_HLSL
#define TOON_SHADER_PASS_HLSL

#define SHADERPASS_FORWARD (0)
#define SHADERPASS_DEPTHONLY (1)
#define SHADERPASS_DEPTHNORMALS (2)
#define SHADERPASS_MOTIONVECTORS (3)
#define SHADERPASS_SHADOWCASTER (4)

#define SHADERPASS_FORWARD_UNLIT (5)
#define SHADERPASS_FORWARD_PARTICLES_UNLIT (6)

#define SHADERPASS_META (7)

#endif // TOON_SHADER_PASS_HLSL